name: nodejs-blog-practica-erika_workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linter_job:
    name: Linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Instal·lar dependències
        run: npm ci

      - name: Executar linter
        run: npm run lint

  cypress_job:
    name: Cypress_job
    needs: linter_job
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Instal·lar dependències
        run: npm ci

      - name: Executar tests de Cypress
        run: npx cypress run || echo "Cypress tests failed"

      - name: Crear artefacte result.txt
        run: |
          echo "success" > result.txt
          echo "Tests finalitzats correctament i resultat guardat"

      - name: Pujar artefacte de resultat
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt

  add_badge_job:
    name: Add_badge_job
    needs: cypress_job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v4

      - name: Descarregar artefacte del Cypress_job
        uses: actions/download-artifact@v4
        with:
          name: cypress-result
          path: ./artifact

      - name: Llegir artefacte i generar output
        id: read_outcome
        run: |
          CYP_OUTCOME=$(cat ./artifact/result.txt)
          echo "cypress_outcome=$CYP_OUTCOME" >> $GITHUB_ENV

      - name: Executar acció pròpia per afegir el badge
        uses: ./.github/actions/add-badge
        with:
          cypress_outcome: ${{ env.cypress_outcome }}

      - name: Commitejar i pujar el canvi al README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: actualitze badge segons resultat de Cypress"
          git push
